version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name dj-app --s3-location s3://codebuild-art/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src
